VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Form_Switchboard"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database

Private Sub Auto_Logo0_Click()

End Sub

Private Sub Box19_Click()

End Sub

Private Sub Detail_Click()

End Sub

Private Sub FormHeader_Click()

End Sub

Private Sub Label1_Click()

End Sub

Private Sub OptionLabel1_BeforeUpdate(Cancel As Integer)

End Sub

Private Sub Picture_Click()

End Sub

Private Sub VerticalShadowBox_Click()

End Sub
